### ISSUE TITLE
Pass URLs or paths to actions

### ISSUE THREAD

**Issue by javierv** [jgdavey/tabletastic#13]
Let's say I've got articles, and in the articles table I want an action to view all the comments in that article, where comments is a nested resource.

Right now I don't think it's possible, since only symbols are allowed for the action. It would be nice to have the ability to pass a URL to the action, as follows:

```
table.data :actions => [:show, :edit, article_comments_path(@article)]
```

Just to give an example.

Thanks.

**Comment by jgdavey** [comment]
Nested resources, and other such complicated cases, are the reason that tabletastic includes the ability to pass a block <code>table.cell</code>. For example, in your case you could try something like:

```
table.data :actions => [:show, :edit] do
  table.cell :comments {|article| link_to "#{article.comments.count} comments", article_comments_path(article) }
end
```

Which should acheive the desired effect.

**Comment by javierv** [comment]
You're right. I forgot I could use an extra cell instead of putting it inside the actions.

Thanks.
