### ISSUE TITLE
how to...

### ISSUE THREAD

**Issue by ghost** [jgdavey/tabletastic#15]
Hi,
I love this plugins but, how to make cell with a complex content, like that :
e.g. :
<% Liste.secteur.where(:id => dossier.secteur).each do |t| %>
<%= t.nom %>
<%end%>

or anything with a block ".each do" ....

It's possible ?
thx for your answer

**Comment by jgdavey** [comment]
Make sure that you've read the documentation carefully. 

I think that you're wondering about the functionality that is provided by the `cell` method:

```
<%= table_for(@posts) do |t|
  t.data do
    t.cell(:title)
    t.cell(:body, :heading => "Content") {|p| truncate(p.body, 30)}
    t.cell(:author) {|p| link_to(p.author.name, p.author) }
  end
end %>
```
