### ISSUE TITLE
Custom action

### ISSUE THREAD

**Issue by kzonov** [jgdavey/tabletastic#23]
Hi!
I really like your gem, but I need some feature, that I cannot find.
I need custom action for row, how can I add it?

**Comment by jgdavey** [comment]
Would something like this work?

``` ruby
= table_for(@posts) do |t|
  = t.data do
     = t.cell :title
     = t.action_link("my_action")
```

**Comment by kzonov** [comment]
No, it's not that I need...
1) Not that syntax. action_link take only two params (like = t.action_link('myaction', 'someprefix'))
2) I need possibility to specify some html options there

**Comment by jgdavey** [comment]
Then perhaps something like this would work:

``` ruby
= table_for(@posts) do |t|
  = t.data do
     = t.cell :title
     = t.cell(:my_action, :heading => nil, :cell_html => { :class => 'something' }) { |font| link_to my_font_path(font) }
```

**Comment by kzonov** [comment]
Yeah! Cool, that's it =)
Thanks to you!
