### ISSUE TITLE
Update gem to use destroy_with_confirm

### ISSUE THREAD

**Issue by sobrinho** [jgdavey/tabletastic#3]
Hi jgdavey,

Thanks for this plugin, really useful. Can you update the gem to use :destroy_with_confirm?

Best regards

**Comment by jgdavey** [comment]
Thanks for your interest in the project! I've updated the gem. You can see the changes in the Changelog. The destroy action by default now uses confirmation. This also deprecates the :destroy_with_confirm action.

Let me know if you have any other issues!
