### ISSUE TITLE
establizing general settings

### ISSUE THREAD

**Issue by andresgutgon** [jgdavey/tabletastic#5]
Is there any way to determine that all tables that i'm going to create have the same html properties

For example I wish that all were created with this form:

<% table_for(@users, :html => {:cellspacing => "0", :cellpadding => "0"}) do |t| %>  

I don't want to set in al my tables the :html hash. It is posible?

**Comment by jgdavey** [comment]
This a reasonable request. I'll try to work it into the rails3 branch.

**Comment by jgdavey** [comment]
I added this with release v0.2.0.pre2 da73784d2e17617ed9dec2925f666d2d20c89231

**Comment by jgdavey** [comment]
Actually, it was this commit that added the feature: f75c76cd019becdc22f0ef366e5b2b5e553830ef
