### ISSUE TITLE
undefined method `table_for' for ...

### ISSUE THREAD

**Issue by jovoto** [jgdavey/tabletastic#8]
Tabletastic seems to be broken:

In my Gemfile:

gem 'tabletastic'

-> bundle install was ok.

$ bundle show tabletastic

/home/my_user/.bundle/ruby/1.8/gems/tabletastic-0.1.3

In my view:

= table_for(@entries) do |e|

Gives me:

undefined method `table_for' for #<#Class:0xb5301a28:0xb52f460c>

Rails version:

rails-3.0.0.beta4

**Comment by jgdavey** [comment]
Although working well, the current gem is still considered prerelease. You can add it to your project by changing the line in your Gemfile to:

```
gem 'tabletastic', '>= 0.2.0.pre5'
```

Also, although it does work well in Rails 3 beta 4, I'd recommend upgrading to Rails 3 RC if at all possible.
