### ISSUE TITLE
Handling namespaces?

### ISSUE THREAD

**Issue by noctivityinc** [jgdavey/tabletastic#9]
I have an admin namespace and a bunch of controllers within, such as "categories."  When I try to use tabletastic to generate the actions it fails because the routes are 

edit_admin_category_path(@category) and not edit_category_path(@category)

I tried the typical rails convension of table_for([:admin, @category]) do which works in formtastic but it failed in tabletastic.

Any idea how to get actions => :all to work with namespaces?

Thanks,

Josh

**Comment by suchasurge** [comment]
Hi.

Try this:

table_for(@category) do |t|
  :actions => :all, :action_prefix => "admin"
end

**Comment by noctivityinc** [comment]
sounds good.  thanks.
